name: Deploy to AWS ECS

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Build and push Docker image to Amazon ECR
      - name: Build, Tag, and Push Docker Image
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ECR_URI: ${{ secrets.AWS_ECR_URI }}
        run: |
          docker build -t $AWS_ECR_URI:latest .
          docker push $AWS_ECR_URI:latest

      # Deploy to Amazon ECS
      - name: Deploy to Amazon ECS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws ecs update-service --cluster my-cluster \
            --service my-service \
            --force-new-deployment
